from __future__ import annotations

from typing import Any, Protocol


class ControlPlanePort(Protocol):
    def start_project(self, project_id: str, title: str, workflow_id: str) -> dict[str, Any]: ...
    def bind_session(self, session_id: str, project_id: str) -> dict[str, Any]: ...
    def record_user_event(self, session_id: str, message: str, source: str = "actual_user_turn") -> dict[str, Any]: ...
    def resolve_gate(self, project_id: str, gate_type: str, user_event_id: str, decision: str) -> dict[str, Any]: ...
    def register_artifact(self, project_id: str, skill_id: str, locator: str, schema_version: str | None = None, metadata: dict[str, Any] | None = None) -> dict[str, Any]: ...
    def attest_validation(self, project_id: str, skill_id: str, passed: bool, validator_id: str, exit_code: int, validated_sha256: str, claims: dict[str, Any] | None = None) -> dict[str, Any]: ...
    def request_transition(self, project_id: str, expected_version: int, to_state: str) -> dict[str, Any]: ...
    def authorize_task(self, project_id: str, skill_id: str, assignee_role: str, upstream_artifact_ids: list[str], expected_output_type: str | None, idempotency_key: str) -> dict[str, Any]: ...
    def attach_runtime_task(self, task_intent_id: str, runtime_system: str, runtime_task_id: str) -> dict[str, Any]: ...
    def authorize_unblock(self, project_id: str, task_intent_id: str) -> dict[str, Any]: ...
    def snapshot(self, project_id: str) -> dict[str, Any]: ...
